### ISSUE TITLE
test fails 

### ISSUE THREAD

**Issue by jstrachan** [openshiftio-vertx-boosters/vertx-http-booster#2]
I just used the `next` git tag and created a project with the openshift.io wizard (code is here: https://github.com/jstrachan/demovertx19) and the test fails:
```
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ demovertx19 ---
[INFO] Surefire report directory: /home/jenkins/workspace/strachan_demovertx19_master-NPNMNXXB7CZ2N3WTGCFB7QXUDHTNKPZKZGT3UDWCENF2SESQOAIA/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.openshift.booster.HttpApplicationTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
May 22, 2017 2:46:38 PM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: e5:f6:d8:93:5e:37:e9:09
Server starter on port 8080
Server starter on port 8080
sh-4.2$ exit
exit
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 241.335 sec <<< FAILURE! - in io.openshift.booster.HttpApplicationTest
callGreetingTest(io.openshift.booster.HttpApplicationTest)  Time elapsed: 121.139 sec  <<< ERROR!
java.util.concurrent.TimeoutException

callGreetingWithParamTest(io.openshift.booster.HttpApplicationTest)  Time elapsed: 120.016 sec  <<< ERROR!
java.util.concurrent.TimeoutException


Results :

Tests in error: 
  HttpApplicationTest.callGreetingTest ? Timeout
  HttpApplicationTest.callGreetingWithParamTest ? Timeout

Tests run: 2, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:16 min
[INFO] Finished at: 2017-05-22T14:50:38+00:00
[INFO] Final Memory: 37M/497M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project demovertx19: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jenkins/workspace/strachan_demovertx19_master-NPNMNXXB7CZ2N3WTGCFB7QXUDHTNKPZKZGT3UDWCENF2SESQOAIA/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project demovertx19: There are test failures.

Please refer to /home/jenkins/workspace/strachan_demovertx19_master-NPNMNXXB7CZ2N3WTGCFB7QXUDHTNKPZKZGT3UDWCENF2SESQOAIA/target/surefire-reports for the individual test results.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /home/jenkins/workspace/strachan_demovertx19_master-NPNMNXXB7CZ2N3WTGCFB7QXUDHTNKPZKZGT3UDWCENF2SESQOAIA/target/surefire-reports for the individual test results.
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:91)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:320)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:892)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:755)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by jstrachan** [comment]
BTW I just upgraded openshift.io to use the new `next` git label for the version of RHOAR quickstarts and got the same test failure - the first build worked fine but when I updated the source and the second build ran the tests failed like above
```
mvn clean -e -U deploy -Dmaven.test.skip=false -P openshift
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Vert.x - HTTP 1.0.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ demov1 ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-java-version) @ demov1 ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven-version) @ demov1 ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ demov1 ---
[INFO] Executing: /bin/sh -c cd '/home/jenkins/workspace/jstrachan_demov1_master-GXVK4R7S57HCINF5SZ5HYCZHT7YCLECWAAKNKPBNS4BUSZKF5CYA' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /home/jenkins/workspace/jstrachan_demov1_master-GXVK4R7S57HCINF5SZ5HYCZHT7YCLECWAAKNKPBNS4BUSZKF5CYA
[INFO] Storing buildNumber: 533311685ccba126ec7d9074f051c0f317da3234 at timestamp: 1495467858808
[INFO] Storing buildScmBranch: jstrachan/demov1/master-1.0.2
[INFO] 
[INFO] --- vertx-maven-plugin:1.0.6:initialize (vmp) @ demov1 ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ demov1 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- fabric8-maven-plugin:3.2.28:resource (fmp) @ demov1 ---
[INFO] F8: Running in OpenShift mode
[INFO] F8: Using docker image name of namespace: jastrachan-jenkins
[INFO] F8: Running generator vertx
[INFO] F8: vertx: Using Docker image fabric8/java-alpine-openjdk8-jdk:1.2 as base / builder
[INFO] F8: Using resource templates from /home/jenkins/workspace/jstrachan_demov1_master-GXVK4R7S57HCINF5SZ5HYCZHT7YCLECWAAKNKPBNS4BUSZKF5CYA/src/main/fabric8
[INFO] F8: fmp-controller: Adding a default Deployment
[INFO] F8: fmp-service: Adding a default Service with ports [8080]
[INFO] F8: vertx-health-check: Adding readiness probe on port 8080, path='/', scheme='HTTP', with initial delay 10 seconds
[INFO] F8: vertx-health-check: Adding liveness probe on port 8080, path='/', scheme='HTTP', with initial delay 180 seconds
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ demov1 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/jenkins/workspace/jstrachan_demov1_master-GXVK4R7S57HCINF5SZ5HYCZHT7YCLECWAAKNKPBNS4BUSZKF5CYA/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ demov1 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/jenkins/workspace/jstrachan_demov1_master-GXVK4R7S57HCINF5SZ5HYCZHT7YCLECWAAKNKPBNS4BUSZKF5CYA/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ demov1 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/jenkins/workspace/jstrachan_demov1_master-GXVK4R7S57HCINF5SZ5HYCZHT7YCLECWAAKNKPBNS4BUSZKF5CYA/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ demov1 ---
[INFO] Surefire report directory: /home/jenkins/workspace/jstrachan_demov1_master-GXVK4R7S57HCINF5SZ5HYCZHT7YCLECWAAKNKPBNS4BUSZKF5CYA/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.openshift.booster.HttpApplicationTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
May 22, 2017 3:44:30 PM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 3f:63:0e:f5:a0:6e:29:76
Server starter on port 8080
Server starter on port 8080
sh-4.2$ exit
exit
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 241.75 sec <<< FAILURE! - in io.openshift.booster.HttpApplicationTest
callGreetingTest(io.openshift.booster.HttpApplicationTest)  Time elapsed: 121.538 sec  <<< ERROR!
java.util.concurrent.TimeoutException

callGreetingWithParamTest(io.openshift.booster.HttpApplicationTest)  Time elapsed: 120.012 sec  <<< ERROR!
java.util.concurrent.TimeoutException


Results :

Tests in error: 
  HttpApplicationTest.callGreetingTest ? Timeout
  HttpApplicationTest.callGreetingWithParamTest ? Timeout

Tests run: 2, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:16 min
[INFO] Finished at: 2017-05-22T15:48:31+00:00
[INFO] Final Memory: 37M/495M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project demov1: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jenkins/workspace/jstrachan_demov1_master-GXVK4R7S57HCINF5SZ5HYCZHT7YCLECWAAKNKPBNS4BUSZKF5CYA/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project demov1: There are test failures.

Please refer to /home/jenkins/workspace/jstrachan_demov1_master-GXVK4R7S57HCINF5SZ5HYCZHT7YCLECWAAKNKPBNS4BUSZKF5CYA/target/surefire-reports for the individual test results.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /home/jenkins/workspace/jstrachan_demov1_master-GXVK4R7S57HCINF5SZ5HYCZHT7YCLECWAAKNKPBNS4BUSZKF5CYA/target/surefire-reports for the individual test results.
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:91)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:320)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:892)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:755)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by cescoffier** [comment]
Burr reported the same issue. I'm trying to reproduce it locally (failing to reproduce so far).

**Comment by jstrachan** [comment]
@cescoffier thanks! here's the source thats failing for me on OSO if thats any help https://github.com/jstrachan/demov1

**Comment by SlavoKrupa** [comment]
@jstrachan there is [test for content of message](https://github.com/jstrachan/demov1/blob/master/src/test/java/io/openshift/booster/HttpApplicationTest.java#L43) which is returned. You have changed the message, but not the test.

**Comment by SlavoKrupa** [comment]
But I understand that the failure description is really bad...

**Comment by jstrachan** [comment]
aha, thanks! :) 

Incidentally I raised a similar issue against the spring boot booster to make it a little easier to demo in a CI / CD setting; it might be nice to share the greeting expression between the app and the test; so there's 1 place you can change the app without breaking the tests: https://github.com/snowdrop/spring-boot-http-booster/issues/42

but sounds like we also need to try fix up the test error reporting too :)

**Comment by cescoffier** [comment]
I've found the issue, gonna fix it tomorrow morning. It's actually a weird behavior of the WebClient. When the "callback" throws an exception it's not caught by the Vert.x exception handler.

I've a workaround until we get this fixed into Vert.x Web Client.

CC @burrsutter.

**Comment by jstrachan** [comment]
@cescoffier thanks!

**Comment by cescoffier** [comment]
The root isssue is: https://github.com/vert-x3/vertx-web/pull/634

**Comment by cescoffier** [comment]
@burrsutter @jstrachan the issue has been fixed in the booster. In addition, the template is now shared between the business logic and the tests (so changing the template does not break the tests).

**Comment by jstrachan** [comment]
many thanks @cescoffier

**Comment by cescoffier** [comment]
BTW, just updated the "next" branch on the catalog.
